spring:
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: web-ui
            client-secret: web-ui
            scope: read,write
            authorization-grant-type: authorization_code
            redirectUri: http://localhost:8080/login/oauth2/code/custom
        provider:
          custom:
            authorization-uri: http://localhost:8083/auth/realms/custom/protocol/openid-connect/auth
            token-uri: http://localhost:8083/auth/realms/custom/protocol/openid-connect/token
            check-token-uri: http://localhost:8083/auth/realms/custom/protocol/openid-connect/check_token
            user-info-uri: http://localhost:8083/auth/realms/custom/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
  thymeleaf:
    cache: false

server:
  port: 8080

logging:
  level:
    org.springframework: INFO

resourceserver:
  api:
    project:
      url: http://localhost:8081/resource-server/api/projects/
        