spring:
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: web-ui
            client-secret: web-ui
            scope: read,write
            authorization-grant-type: client_credentials
        provider:
          custom:
            token-uri: http://localhost:8083/auth/realms/custom/protocol/openid-connect/token

server:
  port: 8080

logging:
  level:
    org.springframework: INFO

resourceserver:
  api:
    project:
      url: http://localhost:8081/resource-server/api/projects/
        